image: continuumio/miniconda3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

before_script:
  - echo "... pulling submodule ..."
  - echo "... Checking runner specifications ..."
  - uname
  - conda create -n venv python=3.8.13
  - conda init bash
  - source ~/.bashrc
  - conda activate venv

pytest:
  stage: test
  script:
    - pip install setuptools==52.0.0
    - conda install conda-forge::blas=*=openblas --file requirements.txt --file requirements-dev.txt
    - pip install numpy_financial==1.0.0
    - pip install -e ./storagevet
    - python -V
    - pip list
    - python run_DERVET.py -h
    - python run_DERVET.py Model_Parameters_Template_DER.csv -v
    - python -m pytest test
  tags:
    - 'docker'
  #only:
  #  - merge_requests
