image: python:3.7

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

before_script:
  - echo "... pulling submodule ..."
  - echo "... Checking runner specifications ..."
  - apt-get update -q -y
  - pip install virtualenv
  - virtualenv dervet-venv
  - source dervet-venv/bin/activate

pytest:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - file ./storagevet/storagevet/Scenario.py
    - pip install -e ./storagevet
    - python -m pytest test --import-mode=importlib
  tags:
    - 'docker'
  only:
    - merge_requests
